### ISSUE TITLE
Create new ticket with formcreator plugins not working (bad redirection)

### ISSUE THREAD

**Issue by tech62** [redddcyclone/glpi-agentmonitor#13] opened 2023-08-23 15:58 UTC
Hi,

I'm using formcreator plugins for making easier the creation of ticket on the user side.
I obtain "the page is not redirect correctly" when i've forcreator plugin activated, when it's disable, it works.

Is it possible to add a parameter to open a custom url ? (from registry / config file)

Thanks !

**Comment by redddcyclone** [comment] 2023-08-25 12:30
Hi @tech62 

That's strange. I use Formcreator here and the standard open ticket page opened normally. Could you post a screenshot of the error?

Anyway, I will be looking forward to add a settings dialog

**Comment by jalcalam** [comment] 2023-08-29 12:46
Hi, 

the same thing happens to me as to tech62 

Uninstalled, glpi_plugin_fomrcreator* tables are removed and reinstalled and same problem. By disabling it tickets redirect bian when making any changes.

GLPI Version 10.0.6

**Comment by redddcyclone** [comment] 2023-11-07 14:10
Hi everyone, sorry for the inactivity on this issue. Adding a settings dialog is still on my plans, but I have not yet decided the approach I'll take on this (administrative issues).

**Comment by sebma** [comment] 2023-12-13 17:54
@redddcyclone Hi, do you have any update on this issue ?

**Comment by Luesp81** [comment] 2024-01-16 14:49
> @redddcyclone Hi, do you have any update on this issue ?

Hi, do you have any update on this issue ?

**Comment by redddcyclone** [comment] 2024-01-16 15:34
Hi @sebma and @Luesp81

Currently I have little time to work on it, but I will be adding a settings dialog so that the ticket URL can be changed.

Sorry for the delay.

**Comment by sebma** [comment] 2024-01-16 17:02
@redddcyclone In the meantime can this path be found in the registry or somehere else ?

**Comment by redddcyclone** [comment] 2024-01-16 17:39
@sebma no, the path is hardcoded.

**Comment by redddcyclone** [comment] 2024-01-18 12:42
@g-bougard Hi,

I'm planning to add a settings dialog to the Monitor so that admins can replace the default "New ticket" URL with a custom provided one. I think the best approach for this would be for the setting to be system-wide, probably saved in the Windows registry.

I think this is a setting that should be set as an argument on installation, as setting this manually on each computer would be a difficult task. However, as the Monitor itself is not installed but bundled with the Agent, I can't do this on my own, nor do I know if it would be plausible for you to add the setting as an argument during the Agent setup, as this argument would be related to the Monitor and not to the Agent itself.

Do you have any suggestions on this case?

Thanks!

**Comment by redddcyclone** [comment] 2024-01-18 19:47
@sebma @Luesp81 @jalcalam @tech62 

Just to provide some updates:

I have already implemented the New ticket page URL settings dialog and the administrative issues I mentioned before are addressed. Opening this setting dialog will require admin rights, so we can save the settings globally.

I'm just waiting for a consensus on if we could deploy this setting massively with the Agent and where exactly it will be saved in the registry. Anyway, the most complex part is already done. After this is resolved, I will commit the changes as soon as possible.

**Comment by g-bougard** [comment] 2024-01-19 07:06
Hi @redddcyclone 

I can add the support for a new configuration value to the installer, this is not a problem.

As a consensus, can I propose you to use the following registry key and if it is not defined or empty, just use a default url based on the agent server configuration as before ?
```
HKEY_LOCALMACHINE/Software/GLPI-Agent/Installer/AgentMonitor-NewTicket-URL
```

This way, I can also propose to use AGENTMONITOR_NEWTICKET_URL as configuration variable for the installer.

Tell me if you have another more accurate suggestion.

**Comment by redddcyclone** [comment] 2024-01-19 11:42
Hi @g-bougard 

That's great! But just for curiosity, why the ```Installer``` key in the registry path?

> As a consensus, can I propose you to use the following registry key and if it is not defined or empty, just use a default url based on the agent server configuration as before ?

I have followed this approach. If the setting is not defined, the code sets the default new ticket URL based on the "server" URL.

All I need to do now in the code is the registry save/load part. That will be quick.

Thanks a lot for the help!

**Comment by sebma** [comment] 2024-01-19 12:38
So I guess, in the future this `AGENTMONITOR_NEWTICKET_URL ` parameter will be documented [here](https://glpi-agent.readthedocs.io/en/latest/installation/windows-command-line.html#command-line-parameters).

**Comment by redddcyclone** [comment] 2024-01-19 14:12
Hi all

Work on this feature is done. I have already commited it to the repository.

I would be glad if you could do a little bit of testing and report possible errors. I already tested everything I could but there can always be a different scenario.

The default behavior is for the Monitor to use the "server" GLPI-Agent parameter with "/front/ticket.form.php" if the registry value is not found. You can change the URL with the "Settings" button. It will create the registry value if it isn't found.
Access to the settings is restricted to admins only, else no one would be able to save the settings as the value resides in ```HKEY_LOCAL_MACHINE```.
When the new installer is released with support for the new ```AGENTMONITOR_NEWTICKET_URL``` parameter, this registry value will be automatically created and the Monitor will read it on startup.

You can download the automatically built artifacts for testing from here:
https://github.com/redddcyclone/glpi-agentmonitor/actions/runs/7584812803
(GLPI-AgentMonitor-Build-x86 and GLPI-AgentMonitor-Build-x64)

Please note that this should **NOT BE USED IN PRODUCTION** yet.

Thanks for the suggestions and help, everyone!

**Comment by Luesp81** [comment] 2024-01-19 15:19
Optimal!! Thank you. I immediately tried but nothing appears on the setting button, it's white. Ideally it would also log in..... I personally set up a script that automatically logs in, I'll post it to you so maybe you can implement everything. Thank you

 

@if (@CodeSection == @Batch) @then 
@echo off
echo var WshShell = WScript.CreateObject("WScript.Shell"); > SendKeys.js
echo WshShell.SendKeys(WScript.Arguments(0)); >> SendKeys.js
set SendKeys=CScript //nologo SendKeys.js
START chrome https://helpdesk.pippo.com
timeout /t 5
%SendKeys% "username"
%SendKeys% "{TAB}"
%SendKeys% "Password"
%SendKeys% "{ENTER}"
:end
del SendKeys.js
goto :EOF

**Comment by redddcyclone** [comment] 2024-01-19 15:49
@Luesp81 

Could you post a screenshot of the problem you mentioned?


Also, thanks for the script, but the problem is the script waits a fixed time to send the key presses, and we can't assume that every computer that uses GLPI is fast enough to open the browser AND the webpage in 5 seconds. And there's also the problem that the user may already be logged in to GLPI, and sending these keys then would cause undefined behavior.

Anyway, I thank you for the contribution!

**Comment by g-bougard** [comment] 2024-01-22 08:50
Hi @redddcyclone 

I thought about `HKEY_LOCALMACHINE/Software/GLPI-Agent/Installer/AgentMonitor-NewTicket-URL` because we can't use `HKEY_LOCALMACHINE/Software/GLPI-Agent` as base registry key as this key is for the agent config and it would generate an error during the agent start if we use it. Also this is a place still use for all other config handled by the installer and not supported by GLPI Agent. If you prefer, we can use another subkey like `HKEY_LOCALMACHINE/Software/GLPI-Agent/Monitor/NewTicket-URL`. Tell me what you prefer, this is still up to you.

Also, I'm not sure to have fully understand, but do you create the key if it doesn't exist ? If yes, I think you should not set it to the computed url by default, and so it should be leaved empty, just in case the admin decides to change the agent `server` url. He should not have to fix it too unless he still set it during installation via `AGENTMONITOR_NEWTICKET_URL`.

@sebma yes, this will be documented on that doc page.

**Comment by Luesp81** [comment] 2024-01-22 08:54
> @Luesp81
> 
> Potresti pubblicare uno screenshot del problema che hai menzionato?
> 
> Inoltre, grazie per lo script, ma il problema è che lo script attende un tempo fisso per inviare le pressioni dei tasti, e non possiamo presumere che ogni computer che utilizza GLPI sia abbastanza veloce da aprire il browser E la pagina web in 5 secondi. E c'è anche il problema che l'utente potrebbe già essere connesso a GLPI e l'invio di queste chiavi causerebbe quindi un comportamento indefinito.
> 
> Comunque, vi ringrazio per il contributo!
![2024-01-19_16-13-04](https://github.com/redddcyclone/glpi-agentmonitor/assets/107414707/2b66eb70-7276-4ad7-82e5-5d16693e60d6)

Here is the screen, can't we study another automatic login method?

**Comment by redddcyclone** [comment] 2024-01-22 12:01
Hi @g-bougard 

I think the ```HKEY_LOCAL_MACHINE\Software\GLPI-Agent\Monitor``` with the ```NewTicket-URL``` value inside it would be a better solution. If you agree, I'll change it in the code.
The key is only created if the user opens the Settings dialog and saves the settings. Also, I'll modify it so that the settings are only saved (and the key created) if the user ***modify*** the URL in the settings dialog. I think it's not a bad thing to have a default in the case that the setting value does not exist in the registry, and the Monitor won't save the computed URL unless the user changes it manually. If you think that's still bad, please report.


@Luesp81 

Sorry, I forgot to add the new strings to the other language string tables. I can't translate the strings though, so I don't know how should I proceed. For now, I think I will leave them in english...

About the automatic login, this is always a difficult thing to do if not via Kerberos SSO. The Monitor only opens the browser with the command line, I can't automate the browser process or listen to it. This would only be possible using Internet Explorer through COM, and of course this is not feasible with GLPI. I've already done a similar thing in a project I made in C# for another website, where I got session keys by mimicking the login process and injected it as a cookie ***directly*** in the browser database (in my case, Firefox only). This is a hack and I can't support such a thing (I wouldn't even do it again lol).
Also, why this automatic login thing? You can set the ticket URL to the anonymous new ticket page if you want. If that's not what you want, users would still have to type the username and password in the Monitor if I ever implemented such automatic login thing, so I really don't see any difference in the process. You should really look into implementing Kerberos SSO.

**Comment by redddcyclone** [comment] 2024-01-22 12:09
@Luesp81

I added the missing strings to all the string tables, though they are in english and still need to be translated. Could you test to see if the button is still blank? Built artifacts will be at https://github.com/redddcyclone/glpi-agentmonitor/actions/runs/7610876307

**Comment by g-bougard** [comment] 2024-01-22 13:17
@redddcyclone 

I'm okay to use `HKEY_LOCAL_MACHINE\Software\GLPI-Agent\Monitor\NewTicket-URL`. And I'm okay with your logic to handle its content or missing of content.

**Comment by redddcyclone** [comment] 2024-01-22 13:21
@g-bougard 

Okay, the changes are committed. The only thing left to do is translate the new strings, but I don't know how to proceed with this as the translations to languages other than Brazilian Portuguese and English were not made by myself...

**Comment by g-bougard** [comment] 2024-01-22 13:28
You should trigger all the contributors to update their translation part. I'll make myself a PR for the french translation.

**Comment by redddcyclone** [comment] 2024-01-22 14:01
How should I do this? Opening a new issue in my repo mentioning them? I have never done this up to this point 😬

**Comment by Luesp81** [comment] 2024-01-22 14:34
> Hi @g-bougard
> 
> I think the `HKEY_LOCAL_MACHINE\Software\GLPI-Agent\Monitor` with the `NewTicket-URL` value inside it would be a better solution. If you agree, I'll change it in the code. The key is only created if the user opens the Settings dialog and saves the settings. Also, I'll modify it so that the settings are only saved (and the key created) if the user _**modify**_ the URL in the settings dialog. I think it's not a bad thing to have a default in the case that the setting value does not exist in the registry, and the Monitor won't save the computed URL unless the user changes it manually. If you think that's still bad, please report.
> 
> @Luesp81
> 
> Sorry, I forgot to add the new strings to the other language string tables. I can't translate the strings though, so I don't know how should I proceed. For now, I think I will leave them in english...
> 
> About the automatic login, this is always a difficult thing to do if not via Kerberos SSO. The Monitor only opens the browser with the command line, I can't automate the browser process or listen to it. This would only be possible using Internet Explorer through COM, and of course this is not feasible with GLPI. I've already done a similar thing in a project I made in C# for another website, where I got session keys by mimicking the login process and injected it as a cookie _**directly**_ in the browser database (in my case, Firefox only). This is a hack and I can't support such a thing (I wouldn't even do it again lol). Also, why this automatic login thing? You can set the ticket URL to the anonymous new ticket page if you want. If that's not what you want, users would still have to type the username and password in the Monitor if I ever implemented such automatic login thing, so I really don't see any difference in the process. You should really look into implementing Kerberos SSO.

ok
![2024-01-22_15-34-06](https://github.com/redddcyclone/glpi-agentmonitor/assets/107414707/2fde401a-869e-4e26-adc5-81f758c01861)

**Comment by g-bougard** [comment] 2024-01-22 16:13
@redddcyclone 
You have many ways to trigger previous language contributors, but yes, opening a ticket for each language is a good idea. Then you just have to trigger each previous contributor on his language for the related language issue. If one can't contribute again, any other concerned people may decide to propose a translation. And if somebody comes in the future to complain a language is not translated but you have a opened ticket for it, maybe he will propose the missing translation.

**Comment by redddcyclone** [comment] 2024-01-23 00:23
Hi @g-bougard 

Okay, I opened an issue for each language calling the project translators for help. Thanks for the suggestion!

So, the enhancement @tech62 requested on this issue #13 has been worked on and it is already committed. Look forward to seeing this new feature on the next release. I'll be closing this issue now.

Thanks everyone for the suggestions and help!

**Closed as completed by redddcyclone** 2024-01-23 00:23 UTC
Labels: enhancement

**Comment by sebma** [comment] 2024-01-23 13:16
@redddcyclone Hi, what is the PR number for this issue's resolution ?

**Comment by redddcyclone** [comment] 2024-01-23 13:42
Hi @sebma 

I haven't opened a pull request for it. The latest commit 21ae054241837bd7872e1cb254a745feafc0570c has the latest changes, including the settings dialog and the french translation.
